# Generated by Django 3.1.5 on 2021-01-29 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Field1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('st1', models.CharField(max_length=60)),
                ('st2', models.TextField()),
            ],
        ),
    ]
