# Generated by Django 3.1.5 on 2021-01-30 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mytasks', '0003_auto_20210129_0623'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mesagesender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tasksender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.EmailField(max_length=50, unique=True)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mytasks.mesagesender')),
            ],
        ),
        migrations.DeleteModel(
            name='Field',
        ),
    ]
