# Generated by Django 3.1.5 on 2021-01-30 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytasks', '0004_auto_20210130_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesagesender',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='mesagesender'),
        ),
    ]
